### ISSUE TITLE
Shopping list

### ISSUE THREAD

**Issue by isabellebowdey** [AGHSEagleRobotics/frc1388-2022#12]
- [ ] 4 x [2 Pack of micro SD cards/holders](https://www.amazon.com/Micro-Center-Class-Memory-Adapter/dp/B07K81Z6DF/)
- [ ] 1 x [Memory Card Storage Box](https://www.amazon.com/Senkoovi-Aluminum-Resistant-Carrying-Storage/dp/B07DNYXKDS/)
- [ ] 1 x [USB SD Card Reader](https://www.amazon.com/Anker-Portable-Reader-RS-MMC-Micro/dp/B006T9B6R2)

**Comment by scottbot95** [comment]
Items have been ordered
