### ISSUE TITLE
Create Feeder Subsystem/Commands

### ISSUE THREAD

**Issue by scottbot95** [AGHSEagleRobotics/frc1388-2022#17]
Subsystem Requirements:
- [x] Drive forward/reverse
- [x] Brake

Commands:
- [x] Fire
- [x] Eject
- [x] Stop

**Comment by isabellebowdey** [comment]
We created fire, eject, and stop switches, but have yet to assign to buttons. 

!We want to figure out how to make the feeder and shooter run off the same button / run at the same time.

**Comment by isabellebowdey** [comment]
We made the feeder and shooter run off the same button. The feeder is delayed and starts running once the shooter has been within stable range for 2/5th of a second (20 iterations).
