### ISSUE TITLE
Create Intake Subsystem/Commands

### ISSUE THREAD

**Issue by scottbot95** [AGHSEagleRobotics/frc1388-2022#18]
Subsystem Requirements:
- [x] Raise/Lower
- [x] Intake/Eject
- [x] Stop

Commands:
- [x] Raise/Lower
- [x] Intake/Eject
- [x] Stop

**Comment by isabellebowdey** [comment]
Possible control options for the intake:
- When a button is held the intake deploys, when released it retracts
- A button gets pressed and deploys intake, separate button retracts it
- A single button: deploys, then the next press retracts 

Things to think about:
How/ how long do we keep the wheels running after the intake deploys?

**Comment by isabellebowdey** [comment]
We need to account for the transitional feeder, the wheels that are going between the intake and the feeder. This will run with the intake, or run with the feeder, depending on what we want.
