### ISSUE TITLE
Create Climber Subsystem/Commands

### ISSUE THREAD

**Issue by scottbot95** [AGHSEagleRobotics/frc1388-2022#19]
Subsystem Requirements;
- [x] Extend/Retract
- [x] Articulate Arm
  - Manual control
  - Automated Angle control

Commands:
- [x] Extend/Retract
- [x] Manual angle control
- [x] Automatic angle control

**Comment by calvinxp** [comment]
In Constants class, change CANIN_WINCH and CANIN_ARTICULATOR to CANID_WINCH and CANID_ARTICULATOR.

**Comment by jtechau** [comment]
See also #25
