### ISSUE TITLE
fix lambda command subsystem requirements 

### ISSUE THREAD

**Issue by calvinxp** [AGHSEagleRobotics/frc1388-2022#29]
We need to add the subsystem requirements on these lines
https://github.com/AGHSEagleRobotics/frc1388-2022/blob/82dfd60707cc9d56a837a83c15c0d3d692a14ab2/frc1388-2022/src/main/java/frc/robot/RobotContainer.java#L117-L130

**Comment by isabellebowdey** [comment]
Review on Saturday
