### ISSUE TITLE
Camera views

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2022#37]
The robot will have at least two cameras (maybe more).  One of the camera feeds will need to be routed to the dashboard for driver views.  Driver and/or operator controllers will be able to select the camera to be viewed on the dashboard, as per the [Robot Controls](https://docs.google.com/spreadsheets/d/1TEuVnqxcztSx7_xskLJR0lPclqt5JDH7hUzZz6tQlkk/) spec.

**Comment by isabellebowdey** [comment]
Duplicate
