### ISSUE TITLE
Get White Rabbit Ready for PR

### ISSUE THREAD

**Issue by scottbot95** [AGHSEagleRobotics/frc1388-2022#4]
PR is working on setting up a demonstration with a live robot for Dana Elementary School. They want to use White Rabbit so we need to make sure that is in a usable state.

- [x] Verify what code is running on the robot
  - @jtechau Did some research and it seems to be running the correct code 
- [x] Create control map doc

**Comment by scottbot95** [comment]
[Document created with driver controls](https://docs.google.com/document/d/1Z14WTmyM-GAkXgSTNDbVLQMn8agpHqE-p-hraH3yBQg). We noticed some issue with calibration on the right driver stick. Will possibly need to work around this.

**Comment by scottbot95** [comment]
Re-opening. Seems like we might have some calibration issues with the motor controllers and/or joysticks.

**Comment by isabellebowdey** [comment]
At the PR demonstration today only one joystick would connect to the drivetrain at a time, we should examine it.
