### ISSUE TITLE
Set up limit switches for intake, change intake commands 

### ISSUE THREAD

**Issue by isabellebowdey** [AGHSEagleRobotics/frc1388-2022#48]
it works on a when held, talk to drivers about changing this so that wheel runs even when not pressed, if deployed

**Comment by jtechau** [comment]
I would envision that the intake operates on two "when pressed" buttons:
- **Deploy Intake**
  Lowers the arms and starts the intake roller
- **Retract Intake**
  Raises the arms and stops the intake roller

On a side note, it's worth considering whether the transition motor should run a little faster while the intake is operating.  It might be a good idea to design in a separate speed for intake mode,.

**Comment by isabellebowdey** [comment]
We've implemented these commands, we need to figure out the limit switches.

**Comment by isabellebowdey** [comment]
Limit\encoder figured out, and a separate transition speed for intake (transition medium) was added
