### ISSUE TITLE
Create Autonomous Mode Plan

### ISSUE THREAD

**Issue by scottbot95** [AGHSEagleRobotics/frc1388-2022#5]
Will need to work with strategy and design to determine what we want to do and what is possible for our robot. Some potential Ideas:
- Shoot 1, drive away
- Just drive away

**Comment by jtechau** [comment]
Some thoughts:

Probably want to be able to select between a couple options:
- Just drive away
- Shoot, drive away
- Shoot, drive far enough to push the ball in front of the Terminal into the Terminal (would need to happen fast enough to give time for the human player to pick up the ball and shoot before the end of auto)

Driving in a straight line might be sufficient.  Although shooting then driving to the terminal might require a turn as well.  Assumes the drive team can line up the robot to drive in the desired direction, but that also requires aligning the robot to make the initial shot.

The drive team should be able to choose the autonomous mode(s) while setting up on the field (could be through DS dashboard, roboRIO User button, or other input on robot - switches/buttons, USB drive, SD card, etc).  If selectable on the robot, we need to think about how the user controls and indicator(s) will work.

Ideally want (the option) to run the ball intake during autonomous driving, to pick up a ball during auto.  Although this needs to be coordinated carefully or user selectable, to avoid picking up the wrong color ball.  Making ball intake selectable independently of other auto options would be great.

**Comment by scottbot95** [comment]
Google doc created with autonomous plan ideas https://docs.google.com/document/d/1cVWsp89nOGKCKSDn2o1oIzEGELoBSDL_IxG9kCguUVY/edit

**Comment by isabellebowdey** [comment]
We'll implement some basic autonomous commands, probably won't get too complex.
