### ISSUE TITLE
deploy/retract intake without spinning intake wheels or transition

### ISSUE THREAD

**Issue by jv65537** [AGHSEagleRobotics/frc1388-2022#54]
IntakeArmMotor currently blocks battery removal when intake is up. To allow the battery to be removed in the pit, we may need a method to enable the robot and lower the arm so that the battery can be removed/replaced and then raise the arm again.

@isabellbowdey proposed a special command that raises and lowers the arm without running the IntakeWheelSpin or the TransitionMotor.

@calvinxp proposed an idea to have the special command triggered by a controller on input 2 (driver controller on 0, op controller on 1).

**Comment by isabellebowdey** [comment]
Issue isn't needed, fabrication added a carabiner.
