### ISSUE TITLE
Drive Train Code

### ISSUE THREAD

**Issue by scottbot95** [AGHSEagleRobotics/frc1388-2022#6]
As a driver, I want to control the drive train, so that I can control the position and orientation of the robot on the field.

Our robot will be using a differential drive train. We can start setting up at least some basics around driver control.

- [x] #10
  - Curvature Drive Control
  - Arcade Drive Control
  - Tank Drive Control
  - Reverse Mode (flag to invert forward/reverse)
- [x] #13
  - Read driver inputs (joysticks/xbox)
  - Select drive mode (arcade, tank, etc)
    - Shuffleboard selector?
    - Button on controller?
  - Display Current drive mode to ShuffleBoard
  - Select reverse mode
- [x] User input transform
  - [x] Deadband
  - [x] Scaling?

**Comment by jtechau** [comment]
Also need to consider which operator input method(s) to implement - tank, arcade, etc.  Or make it selectable.

**Comment by isabellebowdey** [comment]
We

**Comment by isabellebowdey** [comment]
We tested the drive train code on Knightmare, everything worked.

**Comment by scottbot95** [comment]
Physical drivetrain has been built. Steps to test on the actual drivetrain:
- [ ] Update TalonFX's
- [ ] Program TalonFX's with correct CAN IDs
- [x] Deploy code to robot
- [ ] Test controls
